learning-django/primeiro-projeto/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.show_page, name="show"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random", views.random, name="random")
]

learning-django/primeiro-projeto/first_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encyclopedia/', include('encyclopedia.urls')),

    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")), # include usado para linkarmos os dois arquivos urls (do projeto e da aplicação).
    # o caminho acima é como: execute o que há dentro do arquivo hello.urls
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

learning-django/primeiro-projeto/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path("<str:name>", views.greet, name='greet')
    # o path possui 2 parametros que podemos passar
    # 1: o que será digitado na url após a primeira / | 2: o que será executado quando essa url for chamada
]

learning-django/primeiro-projeto/tasks/urls.py
from django.urls import path
from . import views

# um identificador único para as rotas de cada app
# isso é feito para não gerar um conflito de namespace: duas rotas com o mesmo nome em diferentes aplicações
app_name = 'tasks'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add')
]

learning-django/primeiro-projeto/encyclopedia/views.py
from django.shortcuts import render

import markdown2
from random import choice
from django import forms

from django.http import HttpResponseRedirect

from . import util


# formulário para criar uma nova página:
class CreatePage(forms.Form):
    title = forms.CharField(label="Page Title")
    content = forms.CharField(label="Page Content", widget=forms.Textarea(
        attrs={
            "placeholder": "Type here the content of this especially wiki. The content should be write in Markdown.",
            "style": "width: 600px; height: auto; min-height: 500px;"
        }
    ))


# formulário para carregar uma página existente
class EditContent(forms.Form):
    content = forms.CharField(label="Edit Page Content", widget=forms.Textarea(
        attrs={
            "placeholder": "Type here the content of this especially wiki. The content should be write in Markdown.",
            "style": "width: 600px; height: auto; min-height: 500px;"
        }
    ))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })


def show_page(request, title):
    if util.get_entry(title):
        content = markdown2.markdown(util.get_entry(title))
        return render(request, "encyclopedia/show-requested.html", {
            "content": content,
            "title": title
        })
    else:
        searched = [entry for entry in util.list_entries() if title[0] == entry[0].lower()]
        return render(request, "encyclopedia/page-not-found.html", {
            "title": title,
            "entries": searched,
            "entries2": util.list_entries()
        })


def search(request):
    query = request.POST["q"].lower()
    entries = util.list_entries()

    if query in [entry.lower() for entry in entries]:
        return HttpResponseRedirect(f'wiki/{query}')
    else:
        return show_page(request, query)


def create(request):
    if request.method == 'POST':
        form = CreatePage(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            if util.get_entry(title):
                return render(request, "encyclopedia/error.html", {
                    "msg": "ERROR! This page already exist in our Encyclopedia!"
                })

            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(f"wiki/{title}")
        else:
            return render(request, "encyclopedia/create-page.html", {"form": form})
    else:
        return render(request, "encyclopedia/create-page.html", {"form": CreatePage()})


def edit(request, title):
    if request.method == "GET":
        content = util.get_entry(title)
        if not content:
            return render(request, "encyclopedia/error.html", {
                "msg": f"Sorry, there's no page about {title} yet!"
            })
        return render(request, "encyclopedia/edit.html", {
            "form": EditContent(initial={"content": content}),
            "title": title
        })
    else:
        form = EditContent(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            util.save_entry(title, content)

            return HttpResponseRedirect(f"/encyclopedia/wiki/{title}")
        else:
            return render(request, "encyclopedia/edit.html", {"form": form})


def random(request):
    entry = choice(util.list_entries())
    return HttpResponseRedirect(f"wiki/{entry}")

learning-django/primeiro-projeto/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "hello/index.html")


def greet(request, name):
    # função para dar hello com base no que o usuário digitar na url
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })
    # o terceiro argumento do render é opcional e chamado de context:
    # isto é, toda a informação que eu gostaria de passar para o template, como todas as variáveis.

learning-django/primeiro-projeto/newyear/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    from datetime import datetime

    now = datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

learning-django/primeiro-projeto/tasks/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms


class NewTask(forms.Form):
    task = forms.CharField(label="New Task")
    # priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)


# Create your views here.
def index(request):
    # armazenando as listas em cada sessão do navegador
    if 'tasks' not in request.session:
        request.session['tasks'] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session['tasks']
    })


def add(request):
    # fazer uma verificação no server-side para confirmar se o form está válido
    if request.method == "POST":
        form = NewTask(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session['tasks'] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
    return render(request, "tasks/add.html", {
        "form": NewTask()
    })

learning-django/primeiro-projeto/encyclopedia/templates/encyclopedia/create-page.html
{% extends "encyclopedia/layout.html" %}
{% block title %} Create New Page {% endblock %}

{% block body %}
    <h1>Create New Wiki</h1>
    <form action="{% url 'wiki:create' %}" method="post"> {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

learning-django/primeiro-projeto/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %} Edit Page {% endblock %}
{% block body %}
    <h1>Editing {{ title }} Page</h1>
    <form action="{% url 'wiki:edit' title %}" method="post"> {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

learning-django/primeiro-projeto/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %} Error {% endblock %}

{% block body %}
    <h1>{{ msg }}</h1>
{% endblock %}

learning-django/primeiro-projeto/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block form %}
    <form action="{% url 'wiki:search' %}" method="post"> {% csrf_token %}
        <input class="search"  type="text" name="q" placeholder="Search Encyclopedia">
    </form>
{% endblock %}

{% block body %}
    <h1 style="text-align: center;">All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:show' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

learning-django/primeiro-projeto/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                    <br>
                    {% block form %}
                    {% endblock %}
                <hr>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                <hr>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

learning-django/primeiro-projeto/encyclopedia/templates/encyclopedia/page-not-found.html
{% extends "encyclopedia/layout.html" %}
{% block title %} not found {% endblock %}

{% block body %}
        <h1>Page requested /{{ title }} not exist in our Encyclopedia!</h1>
        {% if entries|length < 1 %}
            <h3 style="margin-top: 10px">You can access the following pages:</h3>
            <ul>
                {% for entry in entries2 %}
                <li><a href="{% url 'wiki:show' entry %}">/{{ entry }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <h3 style="margin-top: 10px">You can access the following pages:</h3>
            <ul>
                {% for entry in entries %}
                <li><a href="{% url 'wiki:show' entry %}">/{{ entry }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
{% endblock %}

learning-django/primeiro-projeto/encyclopedia/templates/encyclopedia/show-requested.html
{% extends "encyclopedia/layout.html" %}
{% block title %} {{ title }} {% endblock %}

{% block body %}
    {{ content | safe }}
    <a href="{% url 'wiki:edit' title %}" style="margin-top: 100px; display: block; text-align: center">Edit Current Page</a>
{% endblock %}

learning-django/primeiro-projeto/hello/templates/hello/greet.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, {{ name }}!</h1>
    </body>
</html>

learning-django/primeiro-projeto/hello/templates/hello/index.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>

learning-django/primeiro-projeto/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Is it new year's?</title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

learning-django/primeiro-projeto/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add New Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View All Tasks</a>
{% endblock %}

learning-django/primeiro-projeto/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>All Tasks</h1>
    <ul>
        {% for v in tasks %}
            <li>{{ v }}</li>
        {% empty %}
            <li>No tasks.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add New Tasks</a>
{% endblock %}

learning-django/primeiro-projeto/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Task</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>